# Generated by Django 5.2.8 on 2025-11-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registartion',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
